# Generated by Django 4.1.6 on 2023-02-27 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dj_shop_cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="items",
            new_name="data",
        ),
    ]
